### ISSUE TITLE
Getting java.lang.IndexOutOfBoundsException: toIndex = 1 when adding filter yields empty result

### ISSUE THREAD

**Issue by ares242** [tyl/mongodbcontainer-addon#11]
I am randomly getting this exception:
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 1
	at java.util.SubList.<init>(AbstractList.java:622)
	at java.util.RandomAccessSubList.<init>(AbstractList.java:775)
	at java.util.AbstractList.subList(AbstractList.java:484)
	at org.tylproject.vaadin.addon.utils.Page.toImmutableList(Page.java:103)
	at org.tylproject.vaadin.addon.utils.Page.subList(Page.java:134)
	at org.tylproject.vaadin.addon.MongoContainer.getItemIds(MongoContainer.java:537)

**Comment by evacchi** [comment]
Are you using the latest version? Are you able to isolate a situation where the bug consistently occurs and the steps to reproduce?

**Comment by ares242** [comment]
I am using the latest version. I am using MongoContainer in a grid, wrapped in a GeneratedPropertyContainer whit vaadin push enabled, it happens some times when adding a filter to the container. I will try to give the exact steps to reproduce.

**Comment by ares242** [comment]
confirmed, it happens when a vaadin filter added to the container yields empty result.

**Comment by evacchi** [comment]
will try and look into it

**Comment by evacchi** [comment]
Are you able to confirm that your issue has been fixed by cloning the repo and installing locally?

    $ mvn install -DskipTest

and then use `1.1-SNAPSHOT` in your `pom.xml`

**Comment by ares242** [comment]
Confirmed my issue has been fixed.
Thank you.

**Comment by evacchi** [comment]
now in public release v1.0.3
